/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Clash Display", "Inter", "sans-serif"],
        brand: ["Groote", "Clash Display", "Inter", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "2xl": "24px",
      },
      boxShadow: {
        soft: "0 2px 12px -4px rgba(23,20,18,0.06)",
        card: "0 20px 60px -20px rgba(23,20,18,0.15)",
        "card-hover": "0 30px 70px -15px rgba(249,98,44,0.22)",
        nav: "0 10px 40px -12px rgba(23,20,18,0.12)",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        primary: {
          DEFAULT: "#F9622C",
          foreground: "#FFFFFF",
          50: "#FFF4EE",
          100: "#FFE6D6",
          200: "#FFC9A8",
          300: "#FFA870",
          400: "#FB8544",
          500: "#F9622C",
          600: "#E24D1B",
          700: "#BC3B14",
          800: "#8F2C10",
          900: "#5F1D0A",
          light: "#FFEDE0",
        },
        "accent-yellow": "#FFC94A",
        accent: { DEFAULT: "#FF8A4C", foreground: "#FFFFFF" },
        ink: { DEFAULT: "#171412" },
        body: { DEFAULT: "#6B645F" },
        muted: { DEFAULT: "#A39A93", foreground: "#6B645F" },
        surface: { DEFAULT: "#FFFFFF" },
        bg: { DEFAULT: "#FFF8F1" },
        border: { DEFAULT: "#F1E9E3" },
        success: { DEFAULT: "#22C55E" },
        danger: { DEFAULT: "#EF4444" },
        "warn-gradient-start": "#FDE68A",
        "warn-gradient-end": "#BEF264",
        "dark-cta": { DEFAULT: "#171412" },
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        shimmer: { "0%": { backgroundPosition: "-1000px 0" }, "100%": { backgroundPosition: "1000px 0" } },
        drift: { "0%,100%": { transform: "translate(0,0)" }, "50%": { transform: "translate(20px,-20px)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        shimmer: "shimmer 2s infinite linear",
        drift: "drift 8s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
